name: CI
on:
  push:
    branches:
      - main
      - bugfix/**
      - feature/**
  workflow_dispatch:
jobs:
  Test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: pwsh
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Set Variables
        run: |
          "BARE_REPOSITORY=$($env:GITHUB_REPOSITORY.split("/")[1])" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append
      - name: Checkout
        uses: actions/checkout@v4
      - name: Read Data
        id: readdata
        uses: ./
        with:
          path: test\CHANGELOG_read.md
      - name: Release
        id: release
        uses: ./
        with:
          path: test\CHANGELOG_release.md
          mode: release
          releaseVersion: 2.0.0
      - name: Add Change
        id: add
        uses: ./
        with:
          path: test\CHANGELOG_add.md
          mode: addchange
          changeType: Added
          changeValue: New Unreleased Addition
      - name: Map Outputs to files
        run: |
          "${{ steps.readdata.outputs.lastVersion }}" | Out-File -FilePath "${{ github.workspace }}\test\read_lastVersion.txt" -NoNewLine
          "${{ steps.readdata.outputs.releaseNotes }}" | Out-File -FilePath "${{ github.workspace }}\test\read_releaseNotes.txt" -NoNewLine
          "${{ steps.release.outputs.lastVersion }}" | Out-File -FilePath "${{ github.workspace }}\test\release_lastVersion.txt" -NoNewLine
          "${{ steps.release.outputs.releaseNotes }}" | Out-File -FilePath "${{ github.workspace }}\test\release_releaseNotes.txt" -NoNewLine
          "${{ steps.add.outputs.lastVersion }}" | Out-File -FilePath "${{ github.workspace }}\test\add_lastVersion.txt" -NoNewLine
          "${{ steps.add.outputs.releaseNotes }}" | Out-File -FilePath "${{ github.workspace }}\test\add_releaseNotes.txt" -NoNewLine
      - name: Run Pester Tests
        id: pester
        uses: zyborg/pester-tests-report@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_name: TestResults_${{ runner.os }}
          tests_fail_step: true
          gist_name: ${{ env.BARE_REPOSITORY }}_TestResults_${{ runner.os }}.md
          gist_badge_label: ${{ runner.os }}
          gist_token: ${{ secrets.PESTER_GIST_TOKEN }}